package com.protoevo.settings;

import com.protoevo.core.Statistics;
import com.protoevo.env.Environment;
import com.protoevo.maths.Geometry;

public class PlantSettings extends Settings {
    
    public final Parameter<Float> minBirthRadius = new Parameter<>(
            "Min Birth Radius",
            "The minimum radius of a plant at birth.",
            Environment.settings.minParticleRadius.get());
    public final Parameter<Float> maxBirthRadius = new Parameter<>(
            "Max Birth Radius",
            "The maximum radius of a plant at birth.",
            6f / 100f);
    public final Parameter<Float> minPlantGrowth = new Parameter<>(
            "Min Plant Growth",
            "The minimum growth factor a plant can have.",
            0f);
    public final Parameter<Float> maxPlantGrowth = new Parameter<>(
            "Max Plant Growth",
            "The maximum growth factor a plant can have.",
            1.5f);
    public final Parameter<Float> collisionDestructionRate = new Parameter<>(
            "Contact Death Rate",
            "The rate at which a plant's health is reduced when it collides with another non-plant object.",
            Geometry.getCircleArea(maxBirthRadius.get())
                    * Environment.settings.cell.basicParticleMassDensity.get()
    );
    public final Parameter<Float> minHealthToSplit = new Parameter<>(
            "Min Health to Split",
            "Minimum health required to produce children.",
            0.15f);
    // Probabilistic split rate (per sim-second). The old behaviour was
    // "split immediately on reaching maxRadius", which made plant pop
    // churn: every plant at adult size burst on the same tick, parents
    // died, kids grew, repeat. With a rate of 1/30 a mature plant lingers
    // ~30 sec before splitting on average — that lets it act as stable
    // food for protozoa and gives the plant PID a smooth dial to throttle
    // reproduction proportionally instead of an on/off switch.
    public final Parameter<Float> splitRate = new Parameter<>(
            "Plant Split Rate",
            "Probability per sim-second that a mature plant burst-splits.",
            1f / 30f);
    public final Parameter<Float> maxRotationTorque = new Parameter<>(
            "Plant Max Rotation Torque",
            "Maximum torque a plant can apply per frame from its Rotate output.",
            1e-5f);
    // Plants don't need fast cognition — they sit, photosynthesise, and very
    // occasionally express a defensive spike. At the old 0.1s sim-time
    // interval, 1500 plants running reflective GRN updates dominated the
    // fast-forward (128×) frame budget (~1s of GRN per render frame). Bumped
    // to 2s sim time: still plenty for plant adaptation but ~20× cheaper.
    public final Parameter<Float> geneExpressionInterval = new Parameter<>(
            "Gene Expression Interval",
            "The amount of in-simulation time between ticking the Gene Regulatory Networks of plants.",
            Environment.settings.simulationUpdateDelta.get() * 2000f,
            Statistics.ComplexUnit.TIME
    );
    public final Parameter<Float> photosynthesizeEnergyRate = new Parameter<>(
            "Plant Photosynthesize Rate",
            "Energy generated per unit time (adjusted by area) by plants.",
            300f
    );
    public final Parameter<Float> constructionRate = new Parameter<>(
            "Plant Construction Rate",
            "Construction mass generated by plants per unit time.",
            10f
    );
    // Default ON: plants now use the @EvolvableList surface-node mechanism to
    // grow spikes and photoreceptors. With this off, Evolvable.createNew is
    // skipped and plants are spawned through the bare constructor, which
    // leaves surfaceNodes empty — so no plant ever grows a spike/photoreceptor
    // even though the @EvolvableList annotation is in place. Flip this off
    // again for runs that explicitly want non-evolving plants.
    public final Parameter<Boolean> evolutionEnabled = new Parameter<>(
            "Plant Evolution",
            "Whether or not plants pass genetic information to their offspring.",
            true
    );

    public PlantSettings() {
        super("Plant");
    }
}
